spring:
  application:
    name: mscloudgateway
  cloud:
    discovery:
      locator:
        enabled: true
        lower-case-service-id: true

server:
  port: 8080

eurika:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
