spring:
  application:
    name: mscloudgateway
  cloud:
    discovery:
      locator:
        enabled: true
        lower-case-service-id: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://cursoms-eureka-user:crs-uoe-makerussure@localhost:8081/realms/mscourserealm

server:
  port: 8080

eurika:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
